### ISSUE TITLE
About experiments

### ISSUE THREAD

**Issue by xxyzll** [orrzohar/FOMO#4]
Thank you very much for your excellent study. I have some questions about the experiment:
     Are there any additional experiments on the performance of FOMO in the OWD benchmark results? 
     How is the inference speed (FPS) evaluated?

**Comment by orrzohar** [comment]
Hi @xxyzll,

The supplementary has all the typical results on the OWD benchmarks (M/S-OWODB in Table 8, and the WI/A-OSE in Table 9).

I don't believe I ever evaluated FPS -- I generally don't do that because it is very machine-daepenant (e.g., if you run inference on an A100, you would have a higher FPS then on a titanRTX). If you wanted to evaluate FPS on your system, I would just run inference on some 1000 images and see how long that takes (eval and train of course have additional steps, which make them slower). 

Best,
Orr
