### ISSUE TITLE
Is there a training process of FOMO?

### ISSUE THREAD

**Issue by synsin0** [orrzohar/FOMO#5]
Thanks for your great work. I'd like to ask whether there is a training process of FOMO, or we only need to load from pretrained parameters from OWL-ViT? It seems all start scripts are evaluation of different cases? I'm really confused with training.

**Comment by synsin0** [comment]
I may understand that most configs may belong to BASE-ZS/BASE-FS in the paper so they do not need training, which config is for FOMO use?

**Comment by orrzohar** [comment]
Hi @synsin0,
The ones for FOMO are [run_rwd.sh](https://github.com/orrzohar/FOMO/blob/main/configs/run_rwd.sh) and [run_rwd_t2.sh](https://github.com/orrzohar/FOMO/blob/main/configs/run_rwd_t2.sh).

There is some training process, where we finetune the attribute embeddings, however it is very light -- I could release the trained models if you would like. The training is light because it is done in the few-shot regime. 

Best,
Orr

**Comment by synsin0** [comment]
I have successfully started the process of run_rwd.sh and run_rwd_t2.sh and finds the ultra-fast training process. Thanks for your timely response. I will close the issue.

**Comment by orrzohar** [comment]
Hi @synsin0,
Great!
Please note that we will be updating the main table soon as we had some variation between the published values and the reproduced ones -- mostly came from discovering a bug where we had duplicates of the same object in the few_shot_data.json file, leading to a lower few_shot value then expected. 
Best,
Orr
